### ISSUE TITLE
Unable to remove UTM parameters from Bilibili dynamics and articles

### ISSUE THREAD

**Issue by phlinsia** [my-telegram-bots/rewrite_bot#1]
无法移除哔哩哔哩动态和专栏的 UTM 参数。
**Examples:**
`https://b23.tv/HiikdZA`
`https://b23.tv/jhMyc3m`
**Results:**
`https://m.bilibili.com/dynamic/778474101217951784?plat_id=186&share_from=dynamic&share_medium=android&share_plat=android&share_session_id=37d4600a-df88-43ca-b1c2-6d22bc8f46e3&share_source=COPY&share_tag=s_i&timestamp=1680535077&unique_k=HiikdZA`
`https://www.bilibili.com/read/mobile/18911017?plat_id=35&share_from=article`

**Comment by makeding** [comment]
已经添加相应支持。
